name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt

    - name: Install runtime dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install development dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Install OS packages for Tkinter and virtual display
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk xvfb

    - name: Verify headless matplotlib
      run: |
        python -c "import matplotlib; matplotlib.use('Agg'); print('Agg backend OK')"

    - name: Verify Tkinter with virtual display
      run: |
        xvfb-run -a python -c "import tkinter as tk; root = tk.Tk(); root.withdraw(); root.destroy(); print('Tkinter OK with xvfb')"

    - name: Run tests with coverage (headless X display)
      run: |
        xvfb-run -a pytest -q --cov=. --cov-report=xml --cov-report=term

    - name: Upload coverage to artifact
      uses: actions/upload-artifact@v4
      if: matrix.python-version == '3.11'  # Only upload once
      with:
        name: coverage-report
        path: coverage.xml
        retention-days: 30